### ISSUE TITLE
The specified blob does not exist. for url ....

### ISSUE THREAD

**Issue by omidnabavi** [JohnPaton/airbase#7] opened 2020-04-16 17:45 UTC
Dear John,
I am trying to download Airbase data for 2019 and 2020. 
import airbase
client = airbase.AirbaseClient()
client.all_countries
client.all_pollutants

```
for i in range(len(client.all_countries)):
    print (i)
    r = client.request(country=client.all_countries[i], pl=["O3","NO","NO2"],year_from=2019,update_date="2019-01-01 00:00:00")
    r.download_to_file("/path/raw_o3_no_no2_"f"{client.all_countries[i]}"".csv")
```

But I get this error
```
raceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/srvx11/lehre/users/a1276905/.conda/envs/py36/lib/python3.6/site-packages/airbase/airbase.py", line 456, in download_to_file
    r.raise_for_status()??????????????????????????| 3/3 [00:11<00:00,  3.52s/it]
  File "/home/srvx11/lehre/users/a1276905/.conda/envs/py36/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)2/671 [05:08<43:40,  4.38s/it]
requests.exceptions.HTTPError: 404 Client Error: The specified blob does not exist. for url: https://ereporting.blob.core.windows.net/downloadservice/AT_7_48957_2020_timeseries.cs
```
Could you please let me know how to fix it?
Best regards,
Omid.

**Comment by JohnPaton** [comment] 2020-04-16 18:14
Hey Omid, thanks for reaching out!

I'm afraid this is an error on the EEA's database system. If you go to [their portal](http://discomap.eea.europa.eu/map/fme/AirQualityExport.htm) and fill in the settings below (which are what your request is failing on):
![image](https://user-images.githubusercontent.com/18459252/79490998-10f3aa80-801e-11ea-8c8d-899ff94b7305.png)
Then they generate this link to all the CSVs for download:

https://fme.discomap.eea.europa.eu/fmedatastreaming/AirQualityDownload/AQData_Extract.fmw?CountryCode=AT&CityName=&Pollutant=7&Year_from=2019&Year_to=2020&Station=&Samplingpoint=&Source=All&Output=TEXT&UpdateDate=&TimeCoverage=Year

At the time of writing, the last CSV that list is [`https://ereporting.blob.core.windows.net/downloadservice/AT_7_48957_2020_timeseries.csv`](https://ereporting.blob.core.windows.net/downloadservice/AT_7_48957_2020_timeseries.csv). If you click the link, you'll see that that file can't be found, so it EEA must have a problem on their end.

Your easiest solution at the moment is to just skip over the errored files using `raise_for_status=False` (this will just write a warning to you with the filename that failed, instead of crashing your script). You'll have a bit of missing data but the rest should download no problem. So your last line should become

```python
    r.download_to_file("/path/raw_o3_no_no2_"f"{client.all_countries[i]}"".csv",raise_for_status=False )
```

I would _hope_ that EEA will notice and fix this sort of thing relatively quickly. According to their [about page](https://aqportal.discomap.eea.europa.eu/), if you want to contact them about stuff like this you should email aqipr.helpdesk@eionet.europa.eu. 

Sorry I can't do more to help!

**Comment by JohnPaton** [comment] 2020-04-16 18:22
Update: I've done some quick digging and it seems that they have more missing files at the moment. I've found at least 13 in the set `"O3","NO","NO2"` for Austria (AT) since 2019:

https://ereporting.blob.core.windows.net/downloadservice/AT_8_49020_2020_timeseries.csv
https://ereporting.blob.core.windows.net/downloadservice/AT_38_63483_2020_timeseries.csv
https://ereporting.blob.core.windows.net/downloadservice/AT_38_49548_2020_timeseries.csv
https://ereporting.blob.core.windows.net/downloadservice/AT_7_49052_2020_timeseries.csv
https://ereporting.blob.core.windows.net/downloadservice/AT_38_49348_2020_timeseries.csv
https://ereporting.blob.core.windows.net/downloadservice/AT_8_48940_2020_timeseries.csv
https://ereporting.blob.core.windows.net/downloadservice/AT_8_49339_2020_timeseries.csv
https://ereporting.blob.core.windows.net/downloadservice/AT_7_48957_2020_timeseries.csv
https://ereporting.blob.core.windows.net/downloadservice/AT_8_49610_2020_timeseries.csv
https://ereporting.blob.core.windows.net/downloadservice/AT_7_49880_2020_timeseries.csv
https://ereporting.blob.core.windows.net/downloadservice/AT_7_49068_2020_timeseries.csv
https://ereporting.blob.core.windows.net/downloadservice/AT_8_49414_2020_timeseries.csv
https://ereporting.blob.core.windows.net/downloadservice/AT_8_49853_2020_timeseries.csv

Hopefully they are just having technical issues but if this isn't resolved in a day or two I would definitely reach out to them.

**Comment by omidnabavi** [comment] 2020-04-16 19:26
Many thanks for your time.

**Closed** 2020-04-16 19:25 UTC

**Comment by JohnPaton** [comment] 2020-04-17 08:24
I ran a script and found over 1000 broken links across all the data, so I sent them an email. They replied pretty quick:

> Thank you for your email and for flagging this situation. It seems that this has been a recurrent situation this week. The AQ-IPR Helpdesk team is already trying to fix the problem. We will come back to you as soon as the situation is back to normal.
>
> If you have any other problems or questions, please do not hesitate to contact the AQ-IPR Helpdesk.

So hopefully it'll be fixed in a few days! 🚀

**Comment by omidnabavi** [comment] 2020-04-17 08:29
Dear John, 
I would like to thank you for your continued follow-up. I hope it is fixed soon since I need it for an urgent analysis.
Best regards,
Omid.

**Comment by JohnPaton** [comment] 2020-05-29 11:59
Hi Omid, the Help Desk have reached back out to me and notified me that the issue is fixed (which I can confirm). Might be too late for you, but hopefully you were still able to get what you needed!

**Comment by omidnabavi** [comment] 2020-05-29 12:38
Dear John,

Thanks for noting me. No, it is still needed.

Best regards,

Omid.
